### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by donmoderato** [mirsaeedi/SQLCLR-PersianCalendar#2]
hello
my sql server use .net framework version 4.can this be the reason for my error,how can i force sql server use .net 3.5?
and can you generate .dll that use .net 4?

**Comment by mirsaeedi** [comment]
If you are using Sql Server 2012, then the only .NET Framework it can use is 3.5. It's not compatible with other versions. You have to install .Net Framework 3.5 on your server.

**Comment by donmoderato** [comment]
I have .net 3.5 on my laptop,but i have other versions too,and my sql
automatically use version 4

**Comment by donmoderato** [comment]
when i execute this query the version that sql server use is determined.
select * from sys.dm_clr_properties

result: version    v4.0.30319

**Comment by donmoderato** [comment]
do you generate your dll file with visual studio?
please write steps of generating in visual studio for me

**Comment by mirsaeedi** [comment]
The latest version of the [script](https://github.com/mirsaeedi/SQLCLR-Jalali-Date-Utility/blob/master/SqlCLR.JalaliDateUtility/Dist/DeploymentScript.sql) is targeted for latest .NET Framework 4.8. Try it and let me know if it works.

**Comment by donmoderato** [comment]
Yes,your recent version works perfectly
But i l wanted to know the reason(s) of this error,what i sure that is
related to the .net version which sql use.
