### ISSUE TITLE
dddd is not working

### ISSUE THREAD

**Issue by gmareater** [mirsaeedi/SQLCLR-PersianCalendar#3]
hi

thanx for your great work, it's a nice work

now get to bussiness:
'dddd' command does not work correctly, i mean it does not return day name
`select dbo.GregorianToJalali(getdate(),'yyyy MM dddd')`

but other commands seems to work correctly

**Comment by mirsaeedi** [comment]
Hi @gmareater. Thanks for reporting the issue. It got fixed. Run the new deployment script to update the function.

**Comment by gmareater** [comment]
thanx for your fast response,  
but your deployment is missing assembly parts ( you need to redeploy)
thanx in advance
 
```
CREATE ASSEMBLY [SqlCLR.JalaliDateUtility]
    AUTHORIZATION [dbo]

ALTER ASSEMBLY [SqlCLR.JalaliDateUtility]
    DROP FILE ALL

```
