### ISSUE TITLE
Error in installing Utility

### ISSUE THREAD

**Issue by behiunforgiven** [mirsaeedi/SQLCLR-PersianCalendar#4]
Hi, what causes this error?

```
Cannot find either column "dbo" or the user-defined function or aggregate "dbo.GregorianToJalali", or the name is ambiguous.
```

I use SQL Server 2016

**Comment by mirsaeedi** [comment]
Hi @behiunforgiven. I guess SQLCLR Jalali is installed in a different database than the one that you are running your query against. Can you please check that? Are you sure you've installed SQLCLR successfully?

**Comment by behiunforgiven** [comment]
It works in one of my machines well. But I get this error in another machine.
Did I forgot something about installing SQCLR?
