### ISSUE TITLE
Looks like the installation instructions are incomplete

### ISSUE THREAD

**Issue by mrmashal** [mirsaeedi/SQLCLR-PersianCalendar#5]
I'm not familiar with SQL CLR stuff but I couldn't install your scripts using the provided instructions, and some search on the subject shows me I need to build the project, copy the .dll, execute much more SQL than the provided deployment script, etc. Don't you think the documentation should contain more details?
Thanks

**Comment by mirsaeedi** [comment]
The provided instruction suffices for installing the functions. What's the error you are dealing with?

**Comment by mrmashal** [comment]
Here is the steps I do as a total noob😅:

> Make sure you have .NET framework 4.7.2+ installed on your server.

 [OK - Installed v4.8]

> SQL Server 2017+
> sp_configure 'show advanced options', 1;  
> GO  
> RECONFIGURE;  
> GO  
> sp_configure 'clr enabled', 1;  
> GO
> EXEC sp_configure 'clr strict security',0;
> GO
> RECONFIGURE;  
> GO  

[OK]

> Run the Deployment Script in SQL Server Management Studio to generate the Jalali functions in your database.

```
Msg 4121, Level 16, State 1, Line 42
Cannot find either column "dbo" or the user-defined function or aggregate "dbo.GregorianToJalali", or the name is ambiguous.
** An error was encountered during execution of batch. Exiting.
```

Actually the Deployment Script doesn't seem to be "deploying" anything. Maybe some more steps like [this](https://www.codeproject.com/Tips/1009918/Installing-a-CLR-Stored-Procedure-on-SQL-Server) is required🤔

**Comment by mirsaeedi** [comment]
@mrmashal Hi MohammadReza, the deployment script is updated.
